### ISSUE TITLE
Fitbit bidirectional full sync

### ISSUE THREAD

**Issue by zsoltsandor** [Decathlon/hub-decathlon#113]
I like my Geonaute scale, but apparently syncing weight measurements to Fitbit does not work. It would be nice to have.
On the other hand, my activities don't seem to sync to Decathlon Connect. Not sure why. Would be also nice if sleep tracking would sync as well.

Could be all of them bidirectional, always checking data timestamps, data source, whatever is available in the respective APIs, so there is no conflicting data.

**Comment by canssens** [comment]
Hello @zsoltsandor , we only support sport activities for the moment. So we don't synchronize weight and sleep.
About activities, we are going to check if everything is ok.
If you could send your id (located at the bottom of the page https://hub.decathlon.com after login) to infra@decathloncoach.com it could help.
Regards

**Comment by zsoltsandor** [comment]
I have switched tracker brands, so I close this issue.

**Comment by canssens** [comment]
hello @zsoltsandor ok, the issue is still open for us in our backlog. We have to fix the integration of fitbit, actually we have some problems with the async webhook (the message to prevent us that a new activity is available on fitbit).
I hope to fix it this week for the others users of Fitbit.
Regards
